#!/bin/bash
set -e

if [ -n "$DMTS_DEBUG" ]; then
  set -x
fi

: ${DMTS_CONF_DIR:=~/.demitas}
STONE_IMAGE=public.ecr.aws/o0p0b7e7/stone

function usage() {
  echo 'Usage: demitas-pf [ --conf-dir=$DMTS_CONF_DIR ] [-p PROFILE] [ -c CLUSTER ] [ -f family ] -h REMOTE_HOST -r REMOTE_PORT -l LOCAL_PORT' 1>&2
}

function stop_task() {
  echo "Stopping ECS task... (Please wait for a while): $TASK_ID"
  aws ecs stop-task --cluster "$CLUSTER" --task "$TASK_ID" > /dev/null
  echo 'done'
}

if [ $# -eq 0 ]; then
  usage
  exit 0
fi

while getopts p:c:h:r:l:f:-: OPT; do
  optarg="$OPTARG"

  if [ "$OPT" = - ]; then
    OPT="-${OPTARG%%=*}"
    optarg="${OPTARG/${OPTARG%%=*}/}"
    optarg="${optarg#=}"
  fi

  case "-$OPT" in
    -p)
      PROFILE="$optarg"
    ;;
    -c)
      CLUSTER="$optarg"
    ;;
    -h)
      REMOTE_HOST="$optarg"
    ;;
    -r)
      REMOTE_PORT="$optarg"
    ;;
    -l)
      LOCAL_PORT="$optarg"
    ;;
    -f)
      FAMILY="$optarg"
    ;;
    --conf-dir)
      DMTS_CONF_DIR="$optarg"
    ;;
    *)
      usage
      exit 1
    ;;
  esac
done

if [ -z "$REMOTE_HOST" -o -z "$REMOTE_PORT" -o -z "$LOCAL_PORT" ]; then
  usage
  exit 1
fi

if [ -z "$CLUSTER" ]; then
  set +e
  CLUSTER_LINE=( $(grep ^cluster: $DMTS_CONF_DIR/$PROFILE/ecspresso.yml 2> /dev/null) )
  set -e
  CLUSTER="${CLUSTER_LINE[1]}"

  if [ -z "$CLUSTER" ]; then
    echo 'Please specify ECS cluster' 1>&2
    exit 1
  fi
fi

if [ -n "$PROFILE" ]; then
  DEMITAS_OPTS="$DEMITAS_OPTS -p $PROFILE"
fi

if [ -n "$FAMILY" ]; then
  TASK_OVERRIDES='{family:"'"$FAMILY"'"}'
fi

export DMTS_CONF_DIR
CONTAINER_OVERRIDES='{image: "'"$STONE_IMAGE"'", command:["'"$REMOTE_HOST:$REMOTE_PORT"'", "'"$REMOTE_PORT"'"]}'
ECSPRESSO_POTS='--wait-until=running'

echo 'Start ECS task for port forwarding...'

set +e
DEMITAS_OUT=$(demitas $DEMITAS_OPTS -t "$TASK_OVERRIDES" -c "$CONTAINER_OVERRIDES" -- $ECSPRESSO_POTS --dry-run 2>&1 > /dev/null)

if [ $? -ne 0 ]; then
  echo "demitas dry-run failed: demitas $DEMITAS_OPTS -t '$TASK_OVERRIDES' -c '$CONTAINER_OVERRIDES' -- $ECSPRESSO_POTS --dry-run"
  echo $DEMITAS_OUT
  exit 1
fi
set -e

LINE=( $(demitas $DEMITAS_OPTS -t "$TASK_OVERRIDES" -c "$CONTAINER_OVERRIDES" -- $ECSPRESSO_POTS | grep 'Task ID') )
TASK_ID="${LINE[5]}"

if [ -z "$TASK_ID" ]; then
  echo 'error: Started task cannot be found'
fi

echo "ECS task is running: $TASK_ID"

trap stop_task SIGINT

echo 'Start port forwarding...'

ecs-exec-pf -c "$CLUSTER" -t "$TASK_ID" -p "$REMOTE_PORT" -l "$LOCAL_PORT"
